### PR TITLE
Updates MY report code label

### PR DESCRIPTION
**Pull request by Elaine-Krauss-TCG**
#188

### CODE REVIEW

**Review by toddlees — CHANGES_REQUESTED** [review]
How are you going to make this work with migrations.  Are we going to add an additional migration to load the same JSON?  Maybe we could add a migration that changes MY's label to "JULY 31 (MY)".  It'll be idempotent if the migrations run on a new db and will update a db that ran with the old json

**Comment by Elaine-Krauss-TCG** [comment]
> How are you going to make this work with migrations. Are we going to add an additional migration to load the same JSON? Maybe we could add a migration that changes MY's label to "JULY 31 (MY)". It'll be idempotent if the migrations run on a new db and will update a db that ran with the old json

This has actually been done before [here](https://github.com/fecgov/fecfile-web-api/commit/9d3328249df8238891af36c86e7d44bc0409d403).  I'm pretty sure that when Django runs the existing migration and loads in the fixture, it updates the existing objects without issue.

**Comment by toddlees** [comment]
> > How are you going to make this work with migrations. Are we going to add an additional migration to load the same JSON? Maybe we could add a migration that changes MY's label to "JULY 31 (MY)". It'll be idempotent if the migrations run on a new db and will update a db that ran with the old json
> 
> This has actually been done before [here](https://github.com/fecgov/fecfile-web-api/commit/9d3328249df8238891af36c86e7d44bc0409d403). I'm pretty sure that when Django runs the existing migration and loads in the fixture, it updates the existing objects without issue.

I just tested this locally.  If the migration that loads the fixture has been run, it doesn't get run again.

**Comment by Elaine-Krauss-TCG** [comment]
Migration added that patches the MY Report Code Label instance with the correct value.

**Review by toddlees — APPROVED** [review]

**Pull request merged**
